name: Backend-Docker-GCR
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    paths:
      - 'backend/*'
  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    name: Deploy backend
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.BACKEND_SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      # Build docker image
      - name: Build
        run: |-
          docker build backend/data_endpoints/ --file backend/data_endpoints/Dockerfile --tag eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push Image GCR
        run: |-
          docker push eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region ${{ secrets.REGION }} \
          --image "eu.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --port "8080" \
          --allow-unauthenticated

# Following secrets needs to be available in Github Secrets
# BACKEND_SERVICE_NAME=sonar-survey
# PROJECT_ID=sonar-272913
# REGION=europe-north1
# GCLOUD_AUTH= Base64 encoded service acccount
